alias StaffNotes.Accounts
alias StaffNotes.Accounts.User
alias StaffNotes.Markdown
alias StaffNotes.Repo
alias StaffNotesWeb.AuthController
alias StaffNotesWeb.PageController
alias StaffNotesWeb.UserController
alias StaffNotesWeb.AvatarHelpers
alias StaffNotesWeb.ErrorView
alias StaffNotesWeb.LayoutView
alias StaffNotesWeb.PageView
alias StaffNotesWeb.UserView
