language: elixir
elixir:
  - 1.5.1
otp_release:
  - 20.0

branches:
  only:
  - master

dist: trusty
sudo: false
addons:
  postgresql: '9.6'
services:
  - postgresql

install:
  - mix local.rebar --force
  - mix local.hex --force
before_script:
  - cp config/travis.exs config/test.exs
script: ./script/cibuild
