#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

# Install or update npm dependencies
if [ -f "assets/package.json" ]; then
  echo "==> Installing npm dependencies…"
  cd assets
  npm install
  cd -
fi

mix phx.server
